<footer id="footer">
  <p>&copy; 2025 Better Than Boys Studio. All rights reserved.</p>
  <p>
    <a href="https://github.com/ellajaeger23/Better_than_boys_WTP_part1.git" target="_blank">GitHub Repository</a> | 
    <a href="https://ellajaeger23.atlassian.net/jira/software/projects/SCRUM/boards/1" target="_blank">Jira Board</a> | 
    <a href="mailto:betterthanboys@gmail.com">BTB@.university.edu</a>
  </p>
</footer>
